export const products = [
    { id: 1, name: "iPad Pro", price: 1500.00, image: "./images/airpad.png", category: "electronics", description: "Compact wireless earbuds with clear sound and comfortable fit." },
    { id: 2, name: "Bluetooth Speaker", price: 4500.00, image: "./images/bluetooth_speaker.avif", category: "electronics", description: "Portable Bluetooth speaker with deep bass and high-quality sound." },
    { id: 3, name: "Casual Hoodie", price: 3400.00, image: "./images/cousal_hoddie.png", category: "fashion-clothes", description: "Comfortable and stylish hoodie made with soft fabric for everyday fashion wear." },
    { id: 4, name: "Denim Jacket", price: 5200.00, image: "./images/denima_jacket.avif", category: "fashion-clothes", description: "Modern denim jacket with a classic street-style look and durable material." },
    { id: 5, name: "Luxury Female Suit", price: 15000.00, image: "./images/female_suit.webp", category: "fashion-clothes", description: "Elegant female suit for business and formal events." },
    { id: 6, name: "Professional Female Suit", price: 12000.00, image: "./images/female_suit1.webp", category: "fashion-clothes", description: "Polished and professional suit for workplace elegance." },
    { id: 7, name: "Kitchen Utensil Set", price: 9500.00, image: "./images/kitchen.avif", category: "home-material", description: "Complete set of high-quality kitchen tools." },
    { id: 8, name: "Laptop", price: 85000.00, image: "./images/laptop.png", category: "electronics", description: "Powerful laptop for work, study, and entertainment with long battery life." },
    { id: 9, name: "Cultural Men's Outfit", price: 5800.00, image: "./images/men_outfit.png", category: "traditional-clothes", description: "Stylish traditional Ethiopian men's wear designed for holidays and cultural events." },
    { id: 10, name: "Oromo Traditional Clothing", price: 6200.00, image: "./images/oromo_culture.png", category: "traditional-clothes", description: "Colorful Oromo cultural clothing with unique handcrafted designs and premium fabric." },
    { id: 11, name: "Power Bank", price: 2800.00, image: "./images/powerbank.png", category: "electronics", description: "Portable high-capacity power bank for charging devices anywhere." },
    { id: 12, name: "Slim Fit Jeans", price: 3900.00, image: "./images/slimfit_jeans.avif", category: "fashion-clothes", description: "Stylish slim fit jeans with flexible and comfortable high-quality denim fabric." },
    { id: 13, name: "Sneakers", price: 4300.00, image: "./images/sneakers.avif", category: "fashion-clothes", description: "Lightweight fashion sneakers with modern style and comfortable sole design." },
    { id: 14, name: "Modern Sofa", price: 45000.00, image: "./images/sofa.jpg", category: "home-material", description: "Comfortable and stylish modern sofa for your living room." },
    { id: 15, name: "Fashion T-Shirt", price: 1500.00, image: "./images/t-shirt.avif", category: "fashion-clothes", description: "Trendy cotton T-shirt with modern design perfect for casual outfits." },
    { id: 16, name: "Tablet", price: 18500.00, image: "./images/tablet.png", category: "electronics", description: "Modern tablet perfect for reading, gaming, and productivity tasks." },
    { id: 17, name: "Traditional Habesha Dress", price: 4500.00, image: "./images/tradional_dress.jpg", category: "traditional-clothes", description: "Elegant Ethiopian traditional dress with beautiful woven patterns and soft cotton fabric." },
    { id: 18, name: "Traditional Wedding Dress", price: 12500.00, image: "./images/Wedding Dress.png", category: "traditional-clothes", description: "Luxury Ethiopian wedding dress with detailed embroidery and elegant traditional style." },
    { id: 19, name: "Traditional Shawl", price: 1900.00, image: "./images/wedding_female.png", category: "traditional-clothes", description: "Handmade traditional shawl with classic Ethiopian embroidery and lightweight comfort." },
    { id: 20, name: "Women's Fashion Dress", price: 4800.00, image: "./images/women_fashion_dress.avif", category: "fashion-clothes", description: "Elegant fashion dress designed with premium fabric for parties and special occasions." },
    { id: 21, name: "Crystal Wine Glass", price: 800.00, image: "./images/glass.avif", category: "home-material", description: "Exquisite crystal glass for fine dining." },
    { id: 22, name: "Men's Formal Suit", price: 22000.00, image: "./images/suit.avif", category: "fashion-clothes", description: "Premium formal suit for executive look." }
];